# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 617e11207b11bf2c4a4a6a87183b527528e58b48184108f2c48685b63cc6afe0b3816f381396a06295631a545a39a3c6a5ea42a2453f2fe455aa27e1d27ff7c8

test:
  secret_key_base: ca9e542b50207dc09be4520a27c5b789b453e5838f97638d3ad78ae413189a669f9fca1dc3a77387c40b51632cb3649354291e0dfc676eb5c42276745468aaba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
